# Generated by Django 3.0.5 on 2020-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('middlename', models.CharField(default='', max_length=50)),
                ('birthYear', models.IntegerField(default=0)),
                ('deathYear', models.IntegerField(default=0)),
                ('amountOfBooks', models.IntegerField(default=0)),
                ('nobel', models.BooleanField(default=False)),
            ],
        ),
    ]
